name: Build and Deploy carpentryconnect.org Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Install Jekyll and dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Build website
      run:  bundle exec jekyll build --trace
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: '_site'
